[build]
  publish = "public"
  command = "gatsby build"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "'max-age=31536000', 'must-revalidate'"
    Content-Security-Policy = "default-src 'self';"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "geolocation=(self)"